"""
the contents of the reordered variable in AbilityCodingTargetMap.mat

This contains:
AblCodeMap  - map of ability phrase to numeric code relating to ability
complexidx  - 1 if the ability phrase is complex 0 otherwise 
value       - just the values from AblCodeMap
reordered   - ability phrase to human readable key (UT, GT, NT, NA, N)
              where UT = unit target, GT = ground target, 
              NT = no target, NA = no ability, N = other

"""
complex = {
'250mm strike cannons (thor)': 'UT',
'activate/deactivate auto-attack structure': 'NT',
'activate/deactivate auto-repair (mule)': 'N',
'activate/deactivate auto-repair (scv)': 'N',
'archon warp (high templar or dark templar)': 'N',
'arm silo with nuke (ghost academy)': 'N',
'assault mode (viking)': 'NT',
'attack': 'N',
'attack (bunker)': 'N',
'blink (stalker)': 'GT',
'burrow (baneling)': 'NT',
'burrow (drone)': 'NT',
'burrow (hydralisk)': 'NT',
'burrow (infested terran)': 'NT',
'burrow (infestor)': 'NT',
'burrow (queen)': 'NT',
'burrow (roach)': 'NT',
'burrow (ultralisk)': 'NT',
'burrow (zergling)': 'NT',
'calldown extra supplies (orbital command)': 'N',
'calldown mule (orbital command)': 'N',
'cancel': 'NT',
'cancel brood lord morphing (corruptor)': 'N',
'cancel graviton beam': 'UT',
'cancel greater spire upgrade (spire)': 'N',
'cancel hive upgrade (lair)': 'N',
'cancel lair upgrade (hatchery)': 'N',
'cancel orbital command upgrade (command center)': 'N',
'cancel overseer morphing (overlord)': 'N',
'cancel planetary fortress upgrade (command center)': 'N',
'cancel tac nuclear strike (ghost)': 'NA',
'cancel an addon (barracks)': 'N',
'cancel an addon (factory)': 'N',
'cancel an addon (starport)': 'N',
'chrono boost (nexus)': 'N',
'cancel baneling morphing (zergling)': 'N',
'cloak (banshee)': 'NT',
'cloak (ghost)': 'NT',
'contaminate (overseer)': 'UT',
'corruption (corruptor)': 'UT',
'decloak (banshee)': 'NT',
'decloak (ghost)': 'NT',
'emp round (ghost)': 'GT',
'explode (baneling)': 'NT',
'feedback (high templar)': 'UT',
'fighter mode (viking)': 'NT',
'force field (sentry)': 'GT',
'fungal growth (infestor)': 'GT',
'gather resources protoss (probe)': 'N',
'gather resources terran (scv)': 'N',
'generate creep (overlord)': 'NT',
'graviton beam (phoenix)': 'UT',
'guardian shield (sentry)': 'NT',
'halt (on building)': 'NT',
'halt (on unit)': 'NT',
'heal (medivac)': 'NT',
'hold fire': 'NT',
'hold position': 'NT',
'infested terran (infestor)': 'GT',
'land (barracks)': 'NT',
'land (command center)': 'NT',
'land (factory)': 'NT',
'land (orbital command)': 'NT',
'land (starport)': 'NT',
'leave game': 'N',
'lift off (barracks)': 'NT',
'lift off (command center)': 'NT',
'lift off (orbital command)': 'NT',
'lift off (starport)': 'NT',
'load (bunker)': 'NT',
'load (warp prism)': 'NT',
'load all(command center/planetary fortress': 'N',
'lower supply depot (supply depot)': 'NT',
'mass recall (mothership)': 'GT',
'morph to baneling (zergling)': 'N',
'morph to brood lord (corruptor)': 'N',
'morph to overseer (overlord)': 'N',
'move': 'N',
'mutate into greater spire (spire)': 'N',
'mutate into a gateway (warp gate)': 'N',
'neural parasite (infestor)': 'UT',
'patrol': 'NT',
'phasing mode (warp prism)': 'NT',
'psionic storm (high templar)': 'GT',
'raiser supply depot (supply depot)': 'NT',
'repair (mule)': 'NT',
'repair (scv)': 'NT',
'research protoss blink': 'N',
'research protoss charge': 'N',
'research protoss extended thermal lance': 'N',
'research protoss gravitic booster': 'N',
'research protoss gravitic drive': 'N',
'research protoss graviton catapult': 'N',
'research protoss psionic storm': 'N',
'research protoss warp gate': 'N',
'research terran 250mm strike cannons': 'N',
'research terran behemoth reactor': 'N',
'research terran caduceus reactor': 'N',
'research terran cloaking field': 'N',
'research terran combat shield': 'N',
'research terran concussive shells': 'N',
'research terran corvid reactor': 'N',
'research terran durable materials': 'N',
'research terran infernal pre-igniter': 'N',
'research terran moebius reactor': 'N',
'research terran nitro packs': 'N',
'research terran personal cloaking': 'N',
'research terran seeker missile': 'N',
'research terran siege tech': 'N',
'research terran stimpack': 'N',
'research terran weapon refit': 'N',
'research zerg adrenal glands': 'N',
'research zerg burrow': 'N',
'research zerg centrifugal hooks': 'N',
'research zerg chitinous plating': 'N',
'research zerg glial reconstitution': 'N',
'research zerg grooved snipes': 'N',
'research zerg metabolic boost': 'N',
'research zerg neural parasite': 'N',
'research zerg pathogen glands': 'N',
'research zerg pneumatized carapace': 'N',
'research zerg tunneling claws': 'N',
'research zerg ventral sacks': 'N',
'return cargo (drone)': 'N',
'return cargo (mule)': 'N',
'return cargo (probe)': 'N',
'return cargo (scv)': 'N',
'root (spine crawler)': 'N',
'root (spore crawler)': 'N',
'salvage (bunker)': 'N',
'scan move': 'N',
'scanner sweep (orbital command)': 'NA',
'seeker missile (raven)': 'UT',
'set alliance': 'N',
'set rally point (command center)': 'N',
'set rally point (factory)': 'N',
'set rally point (hatchery)': 'N',
'set rally point (nexus)': 'N',
'set worker rally point (hatchery)': 'N',
'set rally point': 'N',
'siege mode (siege tank)': 'NT',
'sniper round (ghost)': 'UT',
'spawn changeling (overseer)': 'GT',
'spawn creep tumor (queen)': 'NT',
'spawn larva (queen)': 'N',
'stimpack (bunker)': 'NT',
'stimpack (marauder)': 'NT',
'stimpack (mixed units)': 'NT',
'stop': 'NT',
'stop (bunker)': 'NT',
'stop generating creep (overlord)': 'N',
'tac nuclear strike (ghost)': 'GT',
'tank mode (siege tank)': 'NT',
'transfusion (queen)': 'UT',
'transport mode (warp prism)': 'NT',
'unburrow (baneling)': 'NT',
'unburrow (drone)': 'NT',
'unburrow (hydralisk)': 'NT',
'unburrow (infestor)': 'NT',
'unburrow (queen)': 'NT',
'unburrow (roach)': 'NT',
'unburrow (ultralisk)': 'NT',
'unburrow (zergling)': 'NT',
'unload all (bunker)': 'NT',
'unload all (command center/planetary fortress)': 'N',
'unload all (nydus worm)': 'NT',
'unload all (warp prism)': 'NT',
'unload all at (medivac)': 'NT',
'unload all at (overlord)': 'NT',
'unload all at (warp prism)': 'NT',
'unload all (medivac)': 'NT',
'unload all (overlord)': 'NT',
'unload unit (bunker)': 'NT',
'unload unit (command center/planetary fortress)': 'NT',
'unload unit (medivac)': 'NT',
'unload unit (nydus worm)': 'NT',
'unload unit (overlord)': 'NT',
'unload unit (warp prism)': 'NT',
'upgrade protoss air armor 1': 'N',
'upgrade protoss air armor 2': 'N',
'upgrade protoss air armor 3': 'N',
'upgrade protoss air weapons 1': 'N',
'upgrade protoss air weapons 2': 'N',
'upgrade protoss air weapons 3': 'N',
'upgrade protoss ground armor 1': 'N',
'upgrade protoss ground armor 2': 'N',
'upgrade protoss ground armor 3': 'N',
'upgrade protoss ground weapons 1': 'N',
'upgrade protoss ground weapons 2': 'N',
'upgrade protoss ground weapons 3': 'N',
'upgrade protoss shield 1': 'N',
'upgrade protoss shield 2': 'N',
'upgrade protoss shield 3': 'N',
'upgrade terran building armor': 'N',
'upgrade terran hi-sec auto tracking': 'N',
'upgrade terran infantry armor 1': 'N',
'upgrade terran infantry armor 2': 'N',
'upgrade terran infantry armor 3': 'N',
'upgrade terran infantry weapons 1': 'N',
'upgrade terran infantry weapons 2': 'N',
'upgrade terran infantry weapons 3': 'N',
'upgrade terran neosteel frame': 'N',
'upgrade terran ship plating 1': 'N',
'upgrade terran ship plating 2': 'N',
'upgrade terran ship plating 3': 'N',
'upgrade terran ship weapons 1': 'N',
'upgrade terran ship weapons 2': 'N',
'upgrade terran ship weapons 3': 'N',
'upgrade terran vehicle plating 1': 'N',
'upgrade terran vehicle plating 2': 'N',
'upgrade terran vehicle plating 3': 'N',
'upgrade terran vehicle weapons 1': 'N',
'upgrade terran vehicle weapons 2': 'N',
'upgrade terran vehicle weapons 3': 'N',
'upgrade zerg flyer attacks 1': 'N',
'upgrade zerg flyer attacks 2': 'N',
'upgrade zerg flyer attacks 3': 'N',
'upgrade zerg flyer carapace 1': 'N',
'upgrade zerg flyer carapace 2': 'N',
'upgrade zerg flyer carapace 3': 'N',
'upgrade zerg ground carapace 1': 'N',
'upgrade zerg ground carapace 2': 'N',
'upgrade zerg ground carapace 3': 'N',
'upgrade zerg melee attacks 1': 'N',
'upgrade zerg melee attacks 2': 'N',
'upgrade zerg melee attacks 3': 'N',
'upgrade zerg missile attacks 1': 'N',
'upgrade zerg missile attacks 2': 'N',
'upgrade zerg missile attacks 3': 'N',
'upgrade to orbital command (command center)': 'N',
'upgrade to planetary fortress (command center)': 'N',
'upgrade to warp gate (gateway)': 'N',
'uproot (spine crawler)': 'NT',
'uproot (spore crawler)': 'NT',
'use ability   5f01': 'N',
'use ability   6e00': 'N',
'use ability   7b42': 'N',
'use ability  12940': 'N',
'use ability  14442': 'N',
'use ability  15d09': 'N',
'use ability  17200': 'N',
'use ability  17801': 'N',
'use ability  17901': 'N',
'use ability  1fa0e': 'N',
'use ability  30422': 'N',
'vortex (mothership)': 'GT',
'yamato cannon (battlecruiser)': 'UT',
'tab': 'N',
'charge (zealot)': 'N',
'enable building attack (baneling)': 'NT',
'gather resources terran (mule)': 'NT',
'gather resources zerg (drone)': 'NT',
'lift off (factory)': 'NT',
'load all(command center/planetary fortress)': 'NT',
'request resources': 'N',
'research protoss anion pulse-crystals': 'N',
'research protoss hallucination': 'N',
'research zerg ventral sacs': 'N',
'send resources to coltrimaster': 'N',
'send resources to dalo': 'N',
'send resources to flawless': 'N',
'send resources to grifo': 'N',
'send resources to nyb': 'N',
'send resources to ponyman': 'N',
'send resources to recon': 'N',
'send resources to sapien': 'N',
'send resources to sasquatch': 'N',
'stimpack (marine)': 'NT',
'stop (burrowed units)': 'N',
'toggle auto-heal (medivac)': 'NT',
'toggle auto-repair (mule)': 'NT',
'toggle auto-repair (scv)': 'NT',
'toggle auto-train interceptor (carrier)': 'NT',
'train an interceptor (carrier)': 'NT',
'use ability    486': 'N',
'use ability    f0f': 'N',
'use ability    f19': 'N',
'use ability    f1d': 'N',
'use ability    f21': 'N',
'use ability    f29': 'N',
'use ability    f2b': 'N',
'use ability    f2f': 'N',
'use ability    f31': 'N',
'use ability    f33': 'N',
'use ability    f35': 'N',
'use ability    f3b': 'N',
'use ability   12c9': 'N',
'use ability   12cb': 'N',
'use ability   12cd': 'N',
'use ability   12cf': 'N',
'use ability   12d1': 'N',
'use ability   12d3': 'N',
'use ability   12d7': 'N',
'use ability   12db': 'N',
'use ability   12dd': 'N',
'use ability   12df': 'N',
'use ability   1304': 'N',
'use ability   1306': 'N',
'use ability   130e': 'N',
'use ability   137a': 'N',
'use ability   1387': 'N',
'use ability   1401': 'N',
'use ability   1403': 'N',
'use ability   170b': 'N',
'use ability   170f': 'N',
'use ability   1ac3': 'N',
'use ability   1d00': 'N',
'use ability   21c0': 'N',
'use ability   2401': 'N',
'use ability   2403': 'N',
'use ability   2d00': 'N',
'use ability   2f40': 'N',
'use ability   31c1': 'N',
'use ability   3200': 'N',
'use ability   33c0': 'N',
'use ability   4741': 'N',
'use ability   4bc0': 'N',
'use ability   4bc1': 'N',
'use ability   4c00': 'N',
'use ability   4c01': 'N',
'use ability   4c03': 'N',
'use ability   4c05': 'N',
'use ability   4c07': 'N',
'use ability   4c40': 'N',
'use ability   4c41': 'N',
'use ability   4c43': 'N',
'use ability   4c81': 'N',
'use ability   4c83': 'N',
'use ability   4c85': 'N',
'use ability   4c87': 'N',
'use ability   4c89': 'N',
'use ability   4c8b': 'N',
'use ability   4c8d': 'N',
'use ability   4c8f': 'N',
'use ability   4c91': 'N',
'use ability   4c93': 'N',
'use ability   4c95': 'N',
'use ability   4c99': 'N',
'use ability   4c9b': 'N',
'use ability   4c9f': 'N',
'use ability   4cc2': 'N',
'use ability   4cc3': 'N',
'use ability   4cc4': 'N',
'use ability   4cc5': 'N',
'use ability   4cc7': 'N',
'use ability   4cc8': 'N',
'use ability   4cc9': 'N',
'use ability   4ccb': 'N',
'use ability   4ccc': 'N',
'use ability   4cce': 'N',
'use ability   4cd0': 'N',
'use ability   4cd2': 'N',
'use ability   4d00': 'N',
'use ability   4d01': 'N',
'use ability   4d40': 'N',
'use ability   4d41': 'N',
'use ability   4d42': 'N',
'use ability   4d43': 'N',
'use ability   4d44': 'N',
'use ability   4d45': 'N',
'use ability   4d47': 'N',
'use ability   4d80': 'N',
'use ability   4d81': 'N',
'use ability   4dc0': 'N',
'use ability   4dc1': 'N',
'use ability   4e00': 'N',
'use ability   4e01': 'N',
'use ability   4e09': 'N',
'use ability   4e0d': 'N',
'use ability   4e80': 'N',
'use ability   4e81': 'N',
'use ability   4ec1': 'N',
'use ability   4f00': 'N',
'use ability   4f01': 'N',
'use ability   4f41': 'N',
'use ability   4fc0': 'N',
'use ability   5041': 'N',
'use ability   5081': 'N',
'use ability   50c0': 'N',
'use ability   50c2': 'N',
'use ability   5101': 'N',
'use ability   5141': 'N',
'use ability   5143': 'N',
'use ability   5145': 'N',
'use ability   5147': 'N',
'use ability   5149': 'N',
'use ability   514b': 'N',
'use ability   514d': 'N',
'use ability   514f': 'N',
'use ability   5151': 'N',
'use ability   5153': 'N',
'use ability   5180': 'N',
'use ability   5181': 'N',
'use ability   51c0': 'N',
'use ability   5241': 'N',
'use ability   5281': 'N',
'use ability   5341': 'N',
'use ability   5380': 'N',
'use ability   5381': 'N',
'use ability   5383': 'N',
'use ability   53c0': 'N',
'use ability   53c1': 'N',
'use ability   5400': 'N',
'use ability   5402': 'N',
'use ability   5404': 'N',
'use ability   5406': 'N',
'use ability   5582': 'N',
'use ability   5601': 'N',
'use ability   5641': 'N',
'use ability   5681': 'N',
'use ability   56c1': 'N',
'use ability   56c3': 'N',
'use ability   56c5': 'N',
'use ability   56c7': 'N',
'use ability   5700': 'N',
'use ability   5741': 'N',
'use ability   5781': 'N',
'use ability   57c0': 'N',
'use ability   57c2': 'N',
'use ability   57c4': 'N',
'use ability   57c6': 'N',
'use ability   57c8': 'N',
'use ability   57ca': 'N',
'use ability   5981': 'N',
'use ability   5983': 'N',
'use ability   5985': 'N',
'use ability   5987': 'N',
'use ability   5a01': 'N',
'use ability   5b01': 'N',
'use ability   5b03': 'N',
'use ability   5b07': 'N',
'use ability   5b41': 'N',
'use ability  12a40': 'N',
'use ability  16040': 'N',
'use ability 104ec1': 'N',
'use ability 104f00': 'N',
'use ability 104f01': 'N',
'use ability 105700': 'N',
}

