"""
use this script to 
add, remove or reorder fields 
for a master table

see gen.pl for the template
and bflmasterfield.py for the base functionality
of these modules / classes
"""

__all__ = [
        "field_playerid",
        "field_gameid",
        "field_player1noquote",
        "field_gamedate",
        "field_gameversion",
        "field_ladderseason",
        "field_timeofday",
        "field_speed",
        "field_format",
        "field_is_competitive",
        "field_gametype",
        "field_mapname",
        "field_winloss",
        "field_maxgametimestamp",
        "field_maxplayertimestamp",
        "field_apm",
        "field_surveyplayerrace",
        "field_numonplayerteam",
        "field_totalplayers",
        "field_opponentmatchup",
        "field_allymatchup",
        "field_failedactionpermin",
        "field_maprcpermin",
        "field_mapatkpermin",
        "field_mapablpermin",
        "field_atkpermin",
        "field_mapatkproportion",
        "field_failstimewasteseconds",
        "field_failssectionscount",
        "field_focusrcpermin",
        "field_focusatkpermin",
        "field_uniquehotkeys",
        "field_hotkeyassignpermin",
        "field_hotkeyselectpermin",
        "field_paccount",
        "field_paccontentsmean",
        "field_pacdurationsmean",
        "field_pacdurationsstd",
        "field_pacactionlatencymax",
        "field_pacactionlatencystd",
        "field_pacactionlatencymean",
        "field_meanpacactiondiffmean",
        "field_meanpacactiondiffstd",
        "field_meanpacactiondiffmax",
        "field_meanpacactiondiffmin",
        "field_nonpacfixdurationsmean",
        "field_nonpacfixdurationsstd",
        "field_pacableactionsoutsidepacprop",
        "field_latencytofixationmean",
        "field_latencytofixationstd",
        "field_actiontypefirstalatencymean",
        "field_actiontypefirstalatencystd",
        "field_actiontypeotheralatencymean",
        "field_actiontypeotheralatencystd",
        "field_actiontypefirstatklatencymean",
        "field_actiontypefirstatklatencystd",
        "field_actiontypeotheratklatencymean",
        "field_actiontypeotheratklatencystd",
        "field_actiontypefirstblatencymean",
        "field_actiontypefirstblatencystd",
        "field_actiontypeotherblatencymean",
        "field_actiontypeotherblatencystd",
        "field_actiontypefirstflatencymean",
        "field_actiontypefirstflatencystd",
        "field_actiontypeotherflatencymean",
        "field_actiontypeotherflatencystd",
        "field_actiontypefirsthklatencymean",
        "field_actiontypefirsthklatencystd",
        "field_actiontypeotherhklatencymean",
        "field_actiontypeotherhklatencystd",
        "field_actiontypefirstmaprcclicklatencymean",
        "field_actiontypefirstmaprcclicklatencystd",
        "field_actiontypeothermaprcclicklatencymean",
        "field_actiontypeothermaprcclicklatencystd",
        "field_actiontypefirstmapatklatencymean",
        "field_actiontypefirstmapatklatencystd",
        "field_actiontypeothermapatklatencymean",
        "field_actiontypeothermapatklatencystd",
        "field_actiontypefirstmapabllatencymean",
        "field_actiontypefirstmapabllatencystd",
        "field_actiontypeothermapabllatencymean",
        "field_actiontypeothermapabllatencystd",
        "field_actiontypefirsttrlatencymean",
        "field_actiontypefirsttrlatencystd",
        "field_actiontypeothertrlatencymean",
        "field_actiontypeothertrlatencystd",
        "field_actiontypefirstsellatencymean",
        "field_actiontypefirstsellatencystd",
        "field_actiontypeothersellatencymean",
        "field_actiontypeothersellatencystd",
        "field_distancebetweenpacsmean",
        "field_distancebetweenfixationsmean",
        "field_fixdurationmean",
        "field_fixdurationmedian",
        "field_fixdurationstd",
        "field_fixcount",
        "field_fixcountpermin",
        "field_paccountoverfixcount",
        "field_pacdurationminusfixduration",
        "field_newviewcost",
        "field_complexabilitypermingt",
        "field_complexabilityperminnorepeatsgt",
        "field_complexabilityperminut",
        "field_complexabilityperminnorepeatsut",
        "field_workerstrainedpermin",
        "field_rcoffscreenall",
        "field_atkoffscreenall",
        "field_rcpropoffscreenall",
        "field_atkpropoffscreenall",
        "field_complexunitsmade",
        "field_buildorder",
        "field_trainordersurvey",
        "field_trainorderopp",
        "field_actionsqueuedpermin",
        "field_buildsqueued",
        "field_totalqueued",
        "field_pacpermin",
        "field_complexunitsmadepermin",
        "field_apmstd",
        "field_pacperminstd",
        "field_workerstrainedperminstd",
        "field_hotkeyassignperminstd",
        "field_hotkeyselectperminstd",
        "field_complexabilitypermingtstd",
        "field_complexunitsmadeperminstd",
        "field_failedactionperminstd",
        "field_maprcperminstd",
        "field_mapatkperminstd",
        "field_mapablperminstd",
        "field_atkperminstd",
        "field_focusrcperminstd",
        "field_focusatkperminstd",
        "field_actionsqueuedperminstd",
        "field_paccontentsmeanstd",
        "field_distancebetweenpacsmeanstd",
        "field_sha1",
]

def keys():
        """
        keys used to create this table
        """
        return ", PRIMARY KEY (`playerid`,`gameid`), " \
                  "KEY `gamedate` (`GameDate`,`TimeOfDay`), " \
                  "KEY `sha1` (`sha1`), " \
                  "KEY `player1noquote` (`player1noquote`) "

def props():
        """
        other table properties for this table
        """
        return "ENGINE=InnoDB DEFAULT CHARSET=utf8"


